version: "3.8"
services:
    express:
        build: ./
        ports:
            - "9898:9898"
        depends_on:
            db:
                condition: service_healthy
    db:
        container_name: db
        image: mysql:5.7
        ports:
            - "3307:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_USER: "mysql"
            MYSQL_PASSWORD: "pass"
            MYSQL_DATABASE: "my_new_db"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10