version: "3.8"
services:
    express:
        container_name: express
        image: express:v1
        build: ./
        ports:
            - "9898:9898"
        depends_on:
            mysql:
                condition: service_healthy
        volumes: 
            - /var/lib/mysql

    mysql:
        container_name: mysql
        image: mysql
        expose:
            - "3306"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_USER: "mysql"
            MYSQL_PASSWORD: "pass"
            MYSQL_DATABASE: "my_new_db"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "0.0.0.0"]
            timeout: 20s
            retries: 10
        