version: "3.8"
services:
    express:
        container_name: express
        image: express:v1
        build: ./
        ports:
            - "9898:9898"
        depends_on:
            mysql:
                condition: service_healthy
        volumes: 
            - /var/lib/mysql

    mysql:
        container_name: mysql
        image: mysql
        expose:
            - "3306"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_HOST: "mysql"
            # MYSQL_USER: "root"
            # MYSQL_PASSWORD: "pass"
            MYSQL_DATABASE: "my_new_db"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "0.0.0.0"]
            timeout: 20s
            retries: 10

    postman:
        image: postman/newman:alpine
        container_name: postmanTests
        command: run DOCKER-express-mysql-postman.postman_collection.json -k -r htmlextra,cli,json --reporter-htmlextra-export="reports/DOCKER-express-mysql-postman.postman_collection.html" --reporter-json-export="reports/DOCKER-express-mysql-postman.postman_collection.json"
        volumes:
            - ./:/etc/newman
        depends_on:
            - "express"
            - "mysql"